### PR TITLE
Add coverage

### PR DESCRIPTION
**Pull request by roman-kiselenko**

### CODE REVIEW

**Comment by k06a** [comment]
Look at the latest line in log here: https://travis-ci.org/mdkis/mdktoken/builds/301332448



Add missing requires to `.solcover.js`.

**Comment by k06a** [comment]
These ones:
```
require('babel-register');
require('babel-polyfill');
```

**Comment by roman-kiselenko** [comment]
@k06a tested locally, the same result. 
```bash
Compiling zeppelin-solidity/contracts/token/MintableToken.sol...
Compiling zeppelin-solidity/contracts/token/PausableToken.sol...
Compiling zeppelin-solidity/contracts/token/SafeERC20.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...
Compiling zeppelin-solidity/contracts/token/TokenTimelock.sol...
/coverageEnv/test/MDKPreICO.js:1
(function (exports, require, module, __filename, __dirname) { import ether from './helpers/ether'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at mdktoken/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
----------------------------|----------|----------|----------|----------|----------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------|----------|----------|----------|----------|----------------|
 contracts/                 |    17.44 |     3.85 |    14.81 |    17.05 |                |
  BonusCrowdsale.sol        |        0 |        0 |        0 |        0 |... 121,122,126 |
  MDKPreICO.sol             |        0 |        0 |        0 |        0 |... 55,66,67,69 |
  MDKToken.sol              |    47.06 |        0 |       60 |    47.06 |... 65,66,68,69 |
  TokenVesting.sol          |    26.92 |    14.29 |       20 |    25.93 |... 108,110,112 |
  TokensCappedCrowdsale.sol |        0 |      100 |        0 |        0 |... 23,24,30,31 |
----------------------------|----------|----------|----------|----------|----------------|
All files                   |    17.44 |     3.85 |    14.81 |    17.05 |                |
----------------------------|----------|----------|----------|----------|----------------|

Istanbul coverage reports generated
Cleaning up...
Some truffle tests failed while running coverage
error Command failed with exit code 1.

```

```js
$> cat .solcover.js 
require('babel-register');
require('babel-polyfill');

module.exports = {
  testCommand: "truffle test",
  copyNodeModules: true
}
```

**Comment by k06a** [comment]
@fishbullet try to copy some config files from here: https://github.com/bitclave/crowdsale or https://github.com/bitclave/Multiownable

**Comment by roman-kiselenko** [comment]
Which config files you're mean? @k06a

**Comment by k06a** [comment]
@fishbullet not sure which of them. I am still not expert in JS, just few months of practice :)

**Comment by k06a** [comment]
You can move BonusCrowdsale.sol and TokensCappedCrowdsale.sol to another directory, because they are tested enough in original repo. I mean move out of contracts directory to increase test coverage.

**Pull request merged**
